const OfficialTimeZonesWithOffset = [
  { name: "Etc/GMT+12", offsetMinutes: -720 },
  { name: "Pacific/Pago_Pago", offsetMinutes: -660 },
  { name: "Pacific/Honolulu", offsetMinutes: -600 },
  { name: "America/Anchorage", offsetMinutes: -540 },
  { name: "America/Los_Angeles", offsetMinutes: -480 },
  { name: "America/Denver", offsetMinutes: -420 },
  { name: "America/Chicago", offsetMinutes: -360 },
  { name: "America/New_York", offsetMinutes: -300 },
  { name: "America/Halifax", offsetMinutes: -240 },
  { name: "America/Argentina/Buenos_Aires", offsetMinutes: -180 },
  { name: "America/Sao_Paulo", offsetMinutes: -180 },
  { name: "Atlantic/Cape_Verde", offsetMinutes: -60 },
  { name: "UTC", offsetMinutes: 0 },
  { name: "Europe/London", offsetMinutes: 60 },
  { name: "Europe/Paris", offsetMinutes: 120 },
  { name: "Europe/Athens", offsetMinutes: 120 },
  { name: "Asia/Jerusalem", offsetMinutes: 120 },
  { name: "Asia/Dubai", offsetMinutes: 240 },
  { name: "Asia/Kolkata", offsetMinutes: 330 },
  { name: "Asia/Kathmandu", offsetMinutes: 345 },
  { name: "Asia/Dhaka", offsetMinutes: 360 },
  { name: "Asia/Bangkok", offsetMinutes: 420 },
  { name: "Asia/Hong_Kong", offsetMinutes: 480 },
  { name: "Asia/Tokyo", offsetMinutes: 540 },
  { name: "Pacific/Auckland", offsetMinutes: 720 },
];

export default OfficialTimeZonesWithOffset;
